USE ridesharing;

LOAD DATA LOCAL INFILE 'C:/Users/3197/Desktop/Ride-Sharing-System-DB/Data/USERS.csv'
INTO TABLE USERS
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'C:/Users/3197/Desktop/Ride-Sharing-System-DB/Data/VEHICLES.csv'
INTO TABLE VEHICLES FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'C:/Users/3197/Desktop/Ride-Sharing-System-DB/Data/LOCATIONS.csv'
INTO TABLE LOCATIONS FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'C:/Users/3197/Desktop/Ride-Sharing-System-DB/Data/RIDES.csv'
INTO TABLE RIDES FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;


LOAD DATA LOCAL INFILE 'C:/Users/3197/Desktop/Ride-Sharing-System-DB/Data/BOOKINGS.csv'
INTO TABLE BOOKINGS FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'C:/Users/3197/Desktop/Ride-Sharing-System-DB/Data/REVIEWS.csv'
INTO TABLE REVIEWS FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'C:/Users/3197/Desktop/Ride-Sharing-System-DB/Data/PAYMENTS.csv'
INTO TABLE PAYMENTS FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;



LOAD DATA LOCAL INFILE 'C:/Users/3197/Desktop/Ride-Sharing-System-DB/Data/IDENTITY_VERIFICATION.csv'
INTO TABLE IDENTITY_VERIFICATION FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;


LOAD DATA LOCAL INFILE 'C:/Users/3197/Desktop/Ride-Sharing-System-DB/Data/VEHICLE_REGISTRATION.csv'
INTO TABLE VEHICLE_REGISTRATION FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'C:/Users/3197/Desktop/Ride-Sharing-System-DB/Data/VERIFICATION_CHECKLIST.csv'
INTO TABLE VERIFICATION_CHECKLIST FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

-- COUNT(*) for each table
SELECT 'USERS' AS TableName, COUNT(*) AS RowCount FROM USERS
UNION ALL
SELECT 'VEHICLES', COUNT(*) FROM VEHICLES
UNION ALL
SELECT 'LOCATIONS', COUNT(*) FROM LOCATIONS
UNION ALL
SELECT 'RIDES', COUNT(*) FROM RIDES
UNION ALL
SELECT 'BOOKINGS', COUNT(*) FROM BOOKINGS
UNION ALL
SELECT 'REVIEWS', COUNT(*) FROM REVIEWS
UNION ALL
SELECT 'PAYMENTS', COUNT(*) FROM PAYMENTS
UNION ALL
SELECT 'IDENTITY_VERIFICATION', COUNT(*) FROM IDENTITY_VERIFICATION
UNION ALL
SELECT 'VEHICLE_REGISTRATION', COUNT(*) FROM VEHICLE_REGISTRATION
UNION ALL
SELECT 'VERIFICATION_CHECKLIST', COUNT(*) FROM VERIFICATION_CHECKLIST;

-- NULL Check on key columns
SELECT 'USERS' AS TableName, COUNT(*) AS NullCount 
FROM USERS WHERE Name IS NULL OR Email IS NULL
UNION ALL
SELECT 'RIDES', COUNT(*) FROM RIDES 
WHERE DriverID IS NULL OR VehicleID IS NULL
UNION ALL
SELECT 'BOOKINGS', COUNT(*) FROM BOOKINGS 
WHERE RideID IS NULL OR PassengerID IS NULL
UNION ALL
SELECT 'PAYMENTS', COUNT(*) FROM PAYMENTS 
WHERE BookingID IS NULL OR Amount IS NULL;


-- FK Integrity Check
SELECT 'Bookings with invalid RideID' AS Check_Type, COUNT(*) AS Count
FROM BOOKINGS b LEFT JOIN RIDES r ON b.RideID = r.RideID
WHERE r.RideID IS NULL
UNION ALL
SELECT 'Bookings with invalid PassengerID', COUNT(*)
FROM BOOKINGS b LEFT JOIN USERS u ON b.PassengerID = u.UserID
WHERE u.UserID IS NULL
UNION ALL
SELECT 'Rides with invalid DriverID', COUNT(*)
FROM RIDES r LEFT JOIN USERS u ON r.DriverID = u.UserID
WHERE u.UserID IS NULL
UNION ALL
SELECT 'Payments with invalid BookingID', COUNT(*)
FROM PAYMENTS p LEFT JOIN BOOKINGS b ON p.BookingID = b.BookingID
WHERE b.BookingID IS NULL
UNION ALL
SELECT 'Reviews with invalid RideID', COUNT(*)
FROM REVIEWS rv LEFT JOIN RIDES r ON rv.RideID = r.RideID
WHERE r.RideID IS NULL;


-- UPDATE: Change status of booking 1 to cancelled
UPDATE BOOKINGS 
SET Status = 'confirmed' 
WHERE BookingID = 1;

-- Verify the update
SELECT BookingID, Status FROM BOOKINGS WHERE BookingID = 1;

-- DELETE: Remove a review with ReviewID 1
DELETE FROM REVIEWS 
WHERE ReviewID = 4;

-- Verify the delete
SELECT COUNT(*) AS RemainingReviews FROM REVIEWS;

